// Generated by CoffeeScript 1.7.1

/* 
Node.js Server, translated in coffeescript
 (c) 2014 Stefan Fodor
 Scraps Websites for Sopcast URLS
 */

(function() {
  var all_sources, cool_tv_scrapper, http, io, jsdom, server, socket;

  http = require('http');

  jsdom = require('jsdom');

  io = require('socket.io');

  all_sources = [];

  server = http.createServer(function(request, response) {
    response.end('hello world');
  });

  server.listen(1337);

  cool_tv_scrapper = function() {
    var find_sopcast_url, source, sources, _i, _len;
    console.log("Scrapping cool-tv.ro...");
    sources = ["http://www.cool-tv.ro/ch/protv.html", "http://www.cool-tv.ro/ch/protv-s2.html", "http://www.cool-tv.ro/ch/protv-s3.html", "http://www.cool-tv.ro/ch/protv-s4.html", "http://www.cool-tv.ro/ch/protv-s5.html", "http://www.cool-tv.ro/ch/protv-s6.html"];
    find_sopcast_url = function(source) {
      jsdom.env({
        url: source,
        scripts: ["http://code.jquery.com/jquery.js"],
        done: function(errors, window) {
          var title, url;
          url = window.$("#SopPlayer").find("[name='SopAddress']").val();
          title = window.$("em").first().html();
          if (url) {
            all_sources.push({
              url: url,
              source: source,
              title: title
            });
          }
        }
      });
    };
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      source = sources[_i];
      find_sopcast_url(source);
    }
  };

  socket = io.listen(server);

  socket.on('connection', function(client) {
    client.emit('url_updated', all_sources);
    client.on('update_url', function() {
      all_sources = [];
      return cool_tv_scrapper();
    });
    return;
  });

  cool_tv_scrapper();

  console.log("All right, dawg!");

}).call(this);
